### ISSUE TITLE
Smashing Barrier components to be hidden before CSS styling

### ISSUE THREAD

**Issue by isonaj** [SSWConsulting/SSW.SmashingBarrier#1]
**Is your feature request related to a problem? Please describe.**
When loading my application, I immediately see un-styled buttons appear first and it makes my application look messy for a few seconds.

**Describe the solution you'd like**
I would like the pre-styled components to be hidden, and the styling to display the components once styled.

**Describe alternatives you've considered**
I'm not sure, perhaps you could create the components once the styles are in place?

**Comment by fenix2222** [comment]
@isonaj test it now

**Comment by isonaj** [comment]
Looks good on my phone. Can try on laptop later

**Comment by isonaj** [comment]
I forgot to come back to this, sorry. Looks great!
